// <auto-generated />
using System;
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211052841_UpdateRuanganSoftDelete")]
    partial class UpdateRuanganSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RuanganId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RuanganId");

                    b.ToTable("Peminjamans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keperluan = "Koordinasi Proyek PBL",
                            NamaPeminjam = "Diaz",
                            RuanganId = 1,
                            Status = "Menunggu",
                            TanggalPinjam = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Keperluan = "Seminar Teknologi Industri",
                            NamaPeminjam = "Rina",
                            RuanganId = 2,
                            Status = "Disetujui",
                            TanggalPinjam = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BlazorApp1.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("integer");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Ruangans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Kapasitas = 12,
                            Lokasi = "Lantai 1",
                            NamaRuangan = "Ruang Rapat Merah"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Kapasitas = 150,
                            Lokasi = "Lantai 2",
                            NamaRuangan = "Aula Serbaguna"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Kapasitas = 20,
                            Lokasi = "Lantai 1",
                            NamaRuangan = "Creative Hub"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Models.Peminjaman", b =>
                {
                    b.HasOne("BlazorApp1.Models.Ruangan", "Ruangan")
                        .WithMany()
                        .HasForeignKey("RuanganId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruangan");
                });
#pragma warning restore 612, 618
        }
    }
}
