// <auto-generated />
using BlazorApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210105204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Kapasitas")
                        .HasColumnType("integer");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ruangans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kapasitas = 12,
                            Lokasi = "Lantai 1",
                            NamaRuangan = "Ruang Rapat Merah"
                        },
                        new
                        {
                            Id = 2,
                            Kapasitas = 150,
                            Lokasi = "Lantai 2",
                            NamaRuangan = "Aula Serbaguna"
                        },
                        new
                        {
                            Id = 3,
                            Kapasitas = 20,
                            Lokasi = "Lantai 1",
                            NamaRuangan = "Creative Hub"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
